### ISSUE TITLE
Obtaining the underlying service handle

### ISSUE THREAD

**Issue by NuSkooler** [mullvad/windows-service-rs#114]
I have needs to utilize `SetServiceObjectSecurity()`. Currently there doesn't seem to be a way to get the underlying service handle, is that correct?

**Comment by pronebird** [comment]
Correct. The underlying ScHandle is private.

**Comment by NuSkooler** [comment]
At least a temporary solution in https://github.com/mullvad/windows-service-rs/pull/115

Thanks!
