### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by davids-work** [mullvad/windows-service-rs#123]
Due to conflicting windows-sys versions, the latest release 0.6.0 is incompatible with many other libraries using Win32 bindings. I note that this crate has bumped its windows-sys version since then, and the version at HEAD works fine for me at least. 

However, having git dependencies cause some issues, like not being able to publish the dependent crates to a registry.

Are there any plans to make a new release to crates.io in the near future?

**Comment by faern** [comment]
I feel the pain of having git dependencies. I also don't like it. I'll see if we can cut a release maybe.

**Comment by faern** [comment]
Working on this in #125

**Comment by faern** [comment]
Published to crates.io and tag pushed: https://github.com/mullvad/windows-service-rs/releases/tag/v0.7.0

**Comment by pronebird** [comment]
Nice! Thanks @faern

**Comment by davids-work** [comment]
Thanks for the quick response!
