### ISSUE TITLE
Not able to perform logging inside created service

### ISSUE THREAD

**Issue by SSinghLenek** [mullvad/windows-service-rs#126]
I am trying to create a service with logging, but logging is working correctly when we run the exe file. But not logging any thing when service is running. 

Also service is crashing if logging is done outside closures.

I am using log4rs for logging.

**Comment by SSinghLenek** [comment]
Thanks you @faern. I was initializing the logger in main. I will try this and update here about the progress.

**Comment by wentaotoyou** [comment]
Running as a windows service, program's default working dir is `c:\windows\systemd32` where the log file should be. We can change  the default setting like this:
```rust
    let exe = std::env::current_exe().unwrap();
    let dir = exe.parent().unwrap();
    std::env::set_current_dir(dir).unwrap();
```
Hope this helps.

**Comment by faern** [comment]
I'm closing this as fixed. Since OP got an answer
