### ISSUE TITLE
Support all service types

### ISSUE THREAD

**Issue by liranringel** [mullvad/windows-service-rs#13]
Thanks for this great crate! It really simplify things.

It could be even better if more service types will be supported (it currently only support `SERVICE_WIN32_OWN_PROCESS`).
Do you have plans to implement it, or, will you accept a PR?

**Comment by pronebird** [comment]
Hi,

Thank you! We’ve only been using `SERVICE_WIN32_OWN_PROCESS` so far. If you happen to work with other kinds of services and willing to contribute, we would gladly accept a PR.

**Comment by pronebird** [comment]
Closing because all other types of services should be supported now (unreleased, see `master`). 

The support for running multiple shared services is not complete yet though.
