### ISSUE TITLE
Retrieving arguments with service_dispatcher::start

### ISSUE THREAD

**Issue by AviateX14** [mullvad/windows-service-rs#28]
I'm a little confused about how arguments should be passed into a registered service. 

It's possible to create a service, and start it, using the following code:

```rust
    let service_args = vec![OsStr::new("some-arg")];

    let service_info = ServiceInfo {
        name: OsString::from(SERVICE_NAME),
        display_name: OsString::from(crate::SERVICE_DISPLAY),
        service_type: SERVICE_TYPE,
        start_type: ServiceStartType::AutoStart,
        error_control: ServiceErrorControl::Normal,
        executable_path: service_binary_path,
        launch_arguments: service_args.iter().map(OsString::from).collect();
        dependencies: vec![],
        account_name: None,
        account_password: None,
    };

    let service = service_manager.create_service(
        service_info,
        ServiceAccess::QUERY_STATUS | ServiceAccess::START,
    )?;
    service.start(&args)?;
```

And then with the following service code, log the arguments supplied:

```rust
pub(in crate) fn run() -> Result<(), OwnErrorType> {
    service_dispatcher::start(SERVICE_NAME, ffi_service_main)?;
    Ok(())
}

define_windows_service!(ffi_service_main, service_main);

pub fn service_main(arguments: Vec<OsString>) {
    trace!("Entered service main hook");
    debug!("Args: {:?}", arguments);

    if let Err(e) = service_worker(arguments) {
        error!("Service error: {}", e);
    }
}
```

This works because args are passed in correctly via the `service.start(&args)` call. However, if I restart the service, meaning that the service registration code is never called, and instead only `run()` is called, the arguments are missing. I can see that the executable is called with it's arguments via the windows service manager, because before `run()` I can get them using StructOpt/Clap/std::env::args, but the one's I supplied in `launch_arguments` are missing. 

This is confusing, what actually populates `Vec<OsString>` for `service_main` when I'm calling it via `service_dispatched::start`?

**Comment by pronebird** [comment]
Hi,

From what I recall, the `launch_arguments` specified in the `ServiceInfo` are persistent, and passed along with `std::env::args` each time the service process starts, while the `arguments` that you receive in `service_main` can only be passed via `Service.start` or by the system. You can perhaps verify that by running `sc start MY_SERVICE_NAME arg1 arg2`.

This is partially outlined in the [corresponding MSDN article](https://docs.microsoft.com/en-us/windows/desktop/api/winsvc/nf-winsvc-startservicew). In certain cases the first argument passed into the `service_main` contains the name of the service, this is perhaps useful in the shared service configuration which we do not support yet.

Normally, the service registration should happen only once and the `launch_arguments` are immutable. For instance, In Mullvad VPN, we do the service registration upon the successful installation of the app.

**Comment by pronebird** [comment]
Closing as resolved.
