### ISSUE TITLE
Set the description of a Windows service?

### ISSUE THREAD

**Issue by edibopp** [mullvad/windows-service-rs#31]
Is there any way to set the description of a Windows service using this library? I am talking about the short text that is shown in the service overview window, see below. For system admins, this makes it easier to identify a service and understand its purpose.

If this feature is not supported yet, how would one go about adding it?

![service-description](https://user-images.githubusercontent.com/3098430/63507955-39e88d80-c4d9-11e9-8b9b-bb861fc5baf5.png)

**Comment by pronebird** [comment]
Hi,

No we don't expose any way to set a service description at the moment. However it should be very trivial to add. 

See how we do that for failure actions:

https://github.com/mullvad/windows-service-rs/blob/master/src/service.rs#L1279

The service description can be set using exactly the same infrastructure we have in place, just fiddle the `SERVICE_CONFIG_DESCRIPTION` flag and follow the MSDN article on the expected input:

https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-changeserviceconfig2w

If you get to implementing this, please consider sending a PR. There is so much we'd like to see added to the crate but the lack of time and priorities are the ones to blame.

**Comment by aepsil0n** [comment]
Hi @pronebird,
Thank you for the quick reply. I may work on this either next week or end of September depending on how many other tasks come my way. But of course, if I manage to get it done, I will send in a PR.

**Comment by aepsil0n** [comment]
So a first pull request is in. I have tried working on a `get_description` as well, but it seems like I can't quite get the conversion from the buffer filled by the API to an `OsString` to work.

**Comment by pronebird** [comment]
@aepsil0n you have to use `WideCStr` to parse the wide string on windows, i.e:

```rust
WideCStr::from_ptr_str(string_ptr).to_os_string()
```

**Comment by yuswitayudi** [comment]
hello, can you help me? @pronebird 
Iam beginner in rust. I am trying to add service windows, and iam read from example install ping service. But when iam install  the service cannot be start, error display is not controller handler from cargo run.

Thanks

**Comment by pronebird** [comment]
@yuswitayudi This thread is about something else. Please follow this thread to resolve your issue: https://github.com/mullvad/windows-service-rs/issues/53.

**Comment by faern** [comment]
Setting service descriptions is now possible on the master branch. We will likely do a release soon. Fixed in #54
