### ISSUE TITLE
PermissionDenied error on Service::start

### ISSUE THREAD

**Issue by zbidwell** [mullvad/windows-service-rs#39]
Hello,

I've made an installer binary that is very similar to your example one, but when I try to call `service.start` after installing, I get a `PermissionDenied` error. I've tried running the exe as administrator but it didn't change anything. This is on Windows 10.

my code:
```rust
// ... Same as example installer.rs main()

    let service = service_manager.create_service(service_info, ServiceAccess::empty())?;

    println!("Service has been installed");

    let service_args: [OsString; 0] = []; // no arguments
    service.start(&service_args)?;

    println!("Service has been started");

    Ok(())
}
```

The output:
```none
Service has been installed
Error: Winapi(Os { code: 5, kind: PermissionDenied, message: "Access is denied." })
```

Any thoughts?

**Comment by pronebird** [comment]
Hi @zbidwell,

When creating a new service or opening an existing one, you have to provide the appropriate `ServiceAccess` mask if you wish to manipulate the returned `service`:

```rs
let service = service_manager.create_service(service_info, ServiceAccess::START)?;
```

**Comment by zbidwell** [comment]
That worked perfectly, thanks!
