### ISSUE TITLE
Allow building as much as possible on non-Windows platform

### ISSUE THREAD

**Issue by nbigaouette** [mullvad/windows-service-rs#47]
I develop on a non-Windows platform a tool that uses the `windows-service` crate.

The Windows specific bits are isolated as much as possible so that almost everything can be built on non-Windows platform (linux and mac). At some point I need to call Windows specific code; in that case it is inside a module that is protected using `#[cfg(target_os = "windows")]`. I also have the same module with the APIs for `#[cfg(not(target_os = "windows"))]` but which uses `unimplemented!()`.

This allows me to have build the whole project against this API while developing. Without this I would not be able to develop on non-Windows. This also allowed my team to use a Linux CI easily available until we could deploy a proper Windows CI.

Could something like that be made for `windows-service`? I don't expect to _run_ the built code but I could at least make sure that the the whole project compiles.

This will allow me to refactor my project on non-Windows platform and be sure that the Windows build will pass. Right now since everything related to `windows-service` is behind a `#[cfg(not(target_os = "windows"))]` I sometimes miss some refactoring parts.

**Comment by pronebird** [comment]
Have you tried removing `#![cfg(windows)]` from `src/lib.rs` and checking if that solves your puzzle?

**Comment by nbigaouette** [comment]
I just tried it. Unfortunately it fails (51 compilation errors). Mainly caused by:
1. the absence of the `winapi` submodules (say `winapi::shared`) on non-Windows platform 
2. usage of `std::os::windows::ffi` to get `OsStr*`

So that would require winapi allowing the same kind of functionality (compilable on non-Windows). Might not be realistic... :(

**Comment by SirWindfield** [comment]
I don't think that this will happen to be honest. `winapi` is (obviously) designed for Windows. The functionality has to be added there and that's just not something that the crate has in scope right now and probably won't have at any point. 

Your approach is the right one though.

**Comment by pronebird** [comment]
I agree with @SirWindfield. I am closing this because, obviously, unless someone builds a phantom copy of winapi-rs, there is absolutely no way we could do anything about it on our side either. To be fair, just a get a VM or install Windows on your computer and code in there.
