### ISSUE TITLE
Example README.md

### ISSUE THREAD

**Issue by LinkTed** [mullvad/windows-service-rs#60]
Perhaps I did not understand it correct, but the example `Handling service events` in the `README.md` file does not work, if you want to stop the service again. You have to set the status by using `set_service_status` method, before return `ServiceControlHandlerResult::NoError`.  Maybe it should be noted in the `README.md` or I did something wrong.

**Comment by pronebird** [comment]
Yes, control events are specifically designed to control the service's state. You have to use `set_service_status` to report the service status in response to control events. You can either report that the service is pending stop or even report it as being stopped immediately before returning from the control handler, it all depends on how your service is designed.

[In examples](https://github.com/mullvad/windows-service-rs/blob/master/examples/ping_service.rs#L128-L136) we simply use a channel to send the shutdown signal back to the main service loop & then break the loop with the eventual call to `set_service_status`:

```
// Tell the system that service has stopped.
status_handle.set_service_status(ServiceStatus {
  service_type: SERVICE_TYPE,
  current_state: ServiceState::Stopped,
  controls_accepted: ServiceControlAccept::empty(),
  exit_code: ServiceExitCode::Win32(0),
  checkpoint: 0,
  wait_hint: Duration::default(),
  process_id: None,
})?;
```

Also note that when reporting the "pending" start/stop/pause events, you have to bump the `checkpoint` counter and provide the `wait_hint` to give the system an estimate for how much long the transition can take. We use a helper struct `PersistentServiceStatus` to handle all that in Mullvad VPN:

https://github.com/mullvad/mullvadvpn-app/blob/master/mullvad-daemon/src/system_service.rs#L202-L288
