### ISSUE TITLE
How to control service stop/restart?

### ISSUE THREAD

**Issue by akaylh** [mullvad/windows-service-rs#61]
If I has service A, How to stop/restart it?

**Comment by pronebird** [comment]
We have examples that touch on similar subjects, i.e: https://github.com/mullvad/windows-service-rs/blob/master/examples/pause_continue.rs

Please refer to documentation for the available API methods on `Service` interface that offers both `start` and `stop` functions:
- [Service::start](https://docs.rs/windows-service/0.3.1/windows_service/service/struct.Service.html#method.start)
- [Service::stop](https://docs.rs/windows-service/0.3.1/windows_service/service/struct.Service.html#method.stop)

You may need to handle errors vigorously as obviously there can be lots of race conditions and possibly use [Service::query_status](https://docs.rs/windows-service/0.3.1/windows_service/service/struct.Service.html#method.query_status) to make sure that the service has fully stopped or started. A naive implementation can be found in examples too: https://github.com/mullvad/windows-service-rs/blob/master/examples/uninstall_service.rs#L15-L19
