### ISSUE TITLE
Can't Access arguements passed via ImagePath

### ISSUE THREAD

**Issue by cboseck** [mullvad/windows-service-rs#63]
Hello I used this tutorial to install a service created with windows-service-rs:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-service?view=powershell-7.1

Now I need to pass an arguemnt to my service.

Windows creates a registry entry as mentioned in the article above.
In ImagePath Value, there are now the args for the program behind the path of the exe.

    pub fn my_service_main(arguments: Vec<OsString>) {

        info!("{:?}", arguments);

        if let Err(e) = run_service() {
            error!("Failed to run service, {:?}", e);
        }
    }

If I run this no arguments except for the service name gets printed out.

Passing arguments via net for sc works.

    net start my-service /asdf

Then /asdf gets printed.

**Comment by pronebird** [comment]
Please see #28 and my answer in particular: https://github.com/mullvad/windows-service-rs/issues/28
