### ISSUE TITLE
Service times out on start when trying to run actix sample code as a windows service.

### ISSUE THREAD

**Issue by nikhilramabhadra** [mullvad/windows-service-rs#67]
I am trying to run [sample code](https://docs.rs/actix-web/latest/actix_web/#examples) on actix website as a windows service. However the service does not start. I can't see a discussions tab so posted it here.
[main.txt](https://github.com/mullvad/windows-service-rs/files/8187626/main.txt)

[Discussion on actix github page](https://github.com/actix/actix-web/discussions/2680)

**Comment by Winor** [comment]
Not helpful but I am having the same problem (but not with actix), I am new to rust and Windows API, so I'm not sure, but it seems like whenever calling block_on cause the service to stop. I discovered that the service does start when using async spawn instead of block_on but then it seems like the funcion is not running at all.

**Comment by nikhilramabhadra** [comment]
I noticed that the executable is running in the task manager. In services.msc the state of the service is "Starting". I am able to send requests to the service using Postman.

![ServiceStartError](https://user-images.githubusercontent.com/75589457/157035578-45e0a5da-3d9d-48d0-8f0d-d69e5f363b0c.png)
[main.txt](https://github.com/mullvad/windows-service-rs/files/8197700/main.txt)
[Cargo_toml.txt](https://github.com/mullvad/windows-service-rs/files/8197702/Cargo_toml.txt)

**Comment by pronebird** [comment]
Hi,

It looks like you use a different service name in the attached code:

```
windows_service::service_dispatcher::start("myservice", ffi_service_main)?;
```

and here:

```
let status_handle = service_control_handler::register("my_service_name", event_handler)?;
```

Note how first it's `myservice` and then it's `my_service_name`. Normally those two should match when you intend to interact with the same service. it would be prudent to use a constant to avoid such mistakes.

We have a well written example of a simple ping service which you can run and inspect or even use as a boilerplate:

https://github.com/mullvad/windows-service-rs/blob/master/examples/ping_service.rs

I am closing this unless you have more evidence that this is a bug in `windows-service-rs`.
