### ISSUE TITLE
Can't set_service_status SERVICE_STOP_PENDING

### ISSUE THREAD

**Issue by olivier-fs** [mullvad/windows-service-rs#72]
Nice job, thanks to this crate I have now a fully functional Windows Service in Rust :-)

I based my own code on your 'ping' example, which uses a mpsc::channel to stop the service.

But I'm facing a "circular reference" problem when trying to report SERVICE_STOP_PENDING :
- the event_handler closure is neat to use the shutdown_tx (moves the value into the closure)
- but obviously enough I can not use the status_handle _inside_ event_handler, since status_handle is returned by service_control_handler::register, which needs the closure as input parameter
- and event_handler must be a closure - not a regular function - because it's signature is FnMut(ServiceControl) so we can't pass the status_handle

I'm thinking about possible failure to comply to stop requests : the SCM will not be told that the service has actually accepted the stop request, and will have no hint about the delay to comply to this request...

In any case the service can report SERVICE_STOPPED (ServiceState::Stopped) at the end of run_service, si it's actually not a real blocker.

I'm using windows-service-0.4.0. 

Am I missing something obvious, or is it actually impossible to report status from within the control handler ?

**Comment by pronebird** [comment]
Hi,

Overall you can pass a copy of `ServiceStatusHandle` around. It's safe to use it from any thread.

If the desire is to access `ServiceStatusHandle` specifically inside of event handler, then I think you can hold the reference to `Arc<Mutex<Option<ServiceStatusHandle>>>` and use it to access status handle from inside the control event handler.

I haven't verified if this code works, but here is a rough example of how to achieve that:

```
// Create mutex with ref counter for status handle
let shared_status_handle: Arc<Mutex<Option<ServiceStatusHandle>>> = Arc::new(Mutex:new(None));

// Clone reference to mutex
let cloned_status_handle = Arc::clone(&shared_status_handle);
let event_handler = move |control_event| -> ServiceControlHandlerResult {
    match control_event {
        ServiceControl::Interrogate => ServiceControlHandlerResult::NoError,

        // Handle stop
        ServiceControl::Stop => {
            // Access the status handle
            let status_handle = cloned_status_handle.lock().unwrap();

            // Do something with status handle...
            // ...

            // Report the desired error code.
            ServiceControlHandlerResult::NoError
            // .. or perhaps a failure to comply?
            // SeviceControlHandlerResult::Other(0xdeadbeef)
        }

        _ => ServiceControlHandlerResult::NotImplemented,
    }
};

// Register event handler
let status_handle = service_control_handler::register("my-service-name", event_handler)?;

// Assign the received status handle
*shared_status_handle.lock().unwrap() = status_handle;
```

Generally we never report anything but `ServiceControlHandlerResult::NoError` in control handler, so we use `mspc::channel` to pass `ServiceControl` to a secondary thread that spawns after the service control handler is already registered. Therefore that thread has access to receiver `mpsc::Receiver<ServiceControl>` and `ServiceStatusHandle` when it spawned. 

Note that you can set a list of accepted control events when updating `ServiceStatus.controls_accepted` at each stage of your service lifecycle, therefore prohibiting unexpected events from reaching your event handler. Hopefully those that are accepted should be handled properly.

**Comment by olivier-fs** [comment]
[Sorry for being late at replying, I'm not yet that lucky to have a fulltime paid job with Rust :-(, still having to cope with legacy c++]

Yes, the classical Arc<Mutex<mycontext>> will do the job. We do not always have to push it to the limits trying to avoid Arc at all costs even when it's perfectly acceptable here (i.e. not within a compute loop).

BTW in my C++ services I use RegisterServiceCtrlHandlerEx() to register not only the handler fn but a service class ; the status handle being one of the attributes, but also having some other useful info e.g. service type, current_state etc.

Current implementation of window_service::register only registers the handler fn ; but it's coherent with the whole crate API being Win32 wrapper functions only, so me be it's kind of overengineering / unidiomatic to map my c++ way of doing things to rust... I'm not sure, I have to write more than one (non-pet project) service in rust to make an opinion.

Threads: I use them in Win32/C++, but I'm doing "background work" with async code (tokio)

    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap();
    rt.block_on(async move {
        my_background-work(<parameters>, shutdown_rx], ).await;
    });

I use a tokio::sync::mpsc::channel rather than the std version. Works great. 

Thank you ! Again, nice crate, this is so much easier to write safe Rust code than C/C++ with tons of global data/handles , and I'm feeling pain now when I have to go back to C++ services...

**Comment by pronebird** [comment]
I am gonna go ahead and close this for now. Please re-open if you feel like there needs to be more clarification.
