### ISSUE TITLE
Some proposals for public API changes

### ISSUE THREAD

**Issue by citreae535** [mullvad/windows-service-rs#92]
### Remove `ServiceDependency`
This abstraction does not seem to do anything useful but some superfluous allocations. We just need to pass whatever callers give us directly to the win32 API and don't need to distinguish between service and group dependencies ourselves. If users want to check if a dependency is a group, they can simply check if it starts with '+'.

### Replace `err-derive` with `thiserror`
Both crates derive `std::error::Error` for an `enum` with slightly different syntax. `thiserror` should be a drop-in replacement and unlikely to break anything. It has some extra features and seems to be better maintained, based on the update time and frequency.

My main motivation for this change is to reduce two functionally similar dependencies to one. `thiserror` is vastly more popluar, therefore users are much more likely to already depend on it rather than `err-derive`. (I just noticed that your VPN client uses `err-derive` but already depended on `thiserror`.)

For comparison, `thiserror` has 76,032,688 total downloads and 8400 dependent crates listed on crates.io when I checked recently. `err-derive` has 2,175,409 total downloads and 71 dependent crates. (This crate happens to be its most downloaded dependent.)

**Comment by pronebird** [comment]
I don't have anything against `ServiceDependency`. I think I was the one who wrote it and I think it's convenient abstraction and does not need to be removed. Micro allocations that it does are negligent on modern computers. It's not 80186 times anymore. It doesn't mean that we should be wasteful, but I think we should draw a line between micro (or even nano) optimizations and real performance bottlenecks vs. convenience and believe it or not, easy to forget what that `+` prefix does. On the other side we maintain a fine line between being merely a wrapper for windows services and being a high level abstraction. We're more on a wrapper side but not entirely without a guilt when comes to abstractions.

Speaking of error handling, [there was an attempt to rewrite it without using external crate](https://github.com/mullvad/windows-service-rs/pull/48). I think it's reasonable and our errors are relative simple and flat and so dropping dependency would be good in my opinion esp. that ancient error chain thing.I don't know why it stalled, 2020 was a mess and I think it should be rebased and revisited.

**Comment by citreae535** [comment]
Well, I had assumed that users of this crate would know what '+' does, but if that's not the case, then yeah, this abstraction is ok.

As for error handling, I've got a look on that PR and it seems they're just manually implementing what `err-derive/thiserror` derives with proc-macros, which [according to `thiserror`](https://docs.rs/thiserror/1.0.38/thiserror/#details), is equivalent and switching between manual and derived implementations is not breaking.

The one thing I don't understand though, is why those nul byte errors are implemented as different variants. Are there any users really matching all those variants and handle them? If one just logs the error and abort, then a single variant like this should be enough. And adding or removing new types of arguments with nul byte errors won't be breaking.

```rust
pub enum Error {
    #[error("{0} contains a nul byte")]
    ArgumentHasNulByte(&'static str)
   // Other variants
}
```

**Comment by pronebird** [comment]
> As for error handling, I've got a look on that PR and it seems they're just manually implementing what err-derive/thiserror derives with proc-macros, which [according to thiserror](https://docs.rs/thiserror/1.0.38/thiserror/#details), is equivalent and switching between manual and derived implementations is not breaking.

I see. I don't know much about `thiserror` crate but `err-derive` hasn't received updates in a while so perhaps we should be looking to migrate to something more maintained. Perhaps @pinkisemils, @dlon or @faern could chime in here. I have nothing against that change especially if it's easy to do.

> The one thing I don't understand though, is why those nul byte errors are implemented as different variants. Are there any users really matching all those variants and handle them? If one just logs the error and abort, then a single variant like this should be enough. And adding or removing new types of arguments with nul byte errors won't be breaking.
> 
> ```rust
> pub enum Error {
>     #[error("{0} contains a nul byte")]
>     ArgumentHasNulByte(&'static str)
>    // Other variants
> }
> ```

I think that happened around time when we stopped exposing widestring errors from crate. https://github.com/mullvad/windows-service-rs/commit/247c10667bcfb9d419c19d964c856575a4036485

And even before that it was really excessive. Overall I think what you suggest makes a lot of sense. For collection arguments we also specify the index of problematic element, i.e:

https://github.com/mullvad/windows-service-rs/blob/64a1fca7b2e6e41ac88925583a27da38daf1be86/src/service.rs#L442

So maybe having two variants should cut it, i.e:

```rs
pub enum Error {
    #[error("{0} contains a nul byte")]
    ArgumentHasNulByte(&'static str)

    #[error("{0} contains a nul byte in element at {1} index")]
    ArgumentArrayElementHasNulByte(&'static str, u32)
}
```

I don't think anyone is really matching against these so while the change is breaking it's likely to be unnoticed by many. So thumbs up from me on this proposal 👍

**Comment by citreae535** [comment]
`err-derive/thiserror` use proc-macros. They make it easier to write and maintain errors at the [cost of compile time](https://www.reddit.com/r/rust/comments/t0w80y/comment/hycs8f4/). If we only have a few error variants, then manual implementation is better for consumers.

**Comment by citreae535** [comment]
This crate contains two sets of functionality, one for implementing Windows services, the other for controlling Windows services through the SCM. It might be possible to split those two, or adding feature flags so that if some users only use this crate to implement services, they don't have to pull in SCM-related stuff.

**Comment by pronebird** [comment]
> This crate contains two sets of functionality, one for implementing Windows services, the other for controlling Windows services through the SCM. It might be possible to split those two, or adding feature flags so that if some users only use this crate to implement services, they don't have to pull in SCM-related stuff.

That's possible to implement. `service_dispatcher` and `service_control_handler` would be a service base and then the rest is SCM. 

Side note: we use the same binary to register itself as a service. In that sense we use both features, but I see that someone could offload the service registration/deregistration to installer script especially because it means access elevation.

**Comment by citreae535** [comment]
@pronebird Thanks for your ideas! Opened #99 to move SCM-related functionality behind a feature flag.
