### ISSUE TITLE
[Release]: new version with updated windows-sys ?

### ISSUE THREAD

**Issue by poliorcetics** [mullvad/windows-service-rs#95]
Could we have a new version with an updated `windows-sys` dependency ? I see it was merged recently, with 9 versions jump at once.

Thanks!

**Comment by faern** [comment]
There are a bunch of other newly opened PRs. We probably want to process and evaluate those first.

**Comment by poliorcetics** [comment]
Are there any issue you want help with ? I'm not sure how much I can help, but I can certainly try

**Comment by pronebird** [comment]
@faern bump

**Comment by faern** [comment]
Ok, let's do this... Did we introduce any breaking change or not? :thinking:

**Comment by faern** [comment]
Yes.. Since swapping from `winapi` to `windows-sys` was a breaking change due to it being in the public API, this must also be breaking since we upgraded `windows-sys`... But I can't currently find where in our API we expose `windows-sys`

**Comment by pronebird** [comment]
See `CHANGELOG.md` for breaking changes: https://github.com/mullvad/windows-service-rs/blob/main/CHANGELOG.md.

**Comment by faern** [comment]
Released! https://crates.io/crates/windows-service/0.6.0
