### ISSUE TITLE
Question: How to retrieve stdout/stderr of rust in Windows service

### ISSUE THREAD

**Issue by okynos** [mullvad/windows-service-rs#96]
Hello,

Thanks for developing this crate. I'm working on an application called [FIM](https://github.com/Achiefs/fim). I use your crate to deploy Windows service.
In some scenarios, the service fails to start and I cannot retrieve the rust log trace that usually comes to stdout and tells me where the error is. The main issue is something related to the code that doesn't happen in foreground execution.
How could I get these logs?

**Comment by pronebird** [comment]
Hi,

There is no stdout in windows service processes from what I remember. 

You have to configure your logger to persist messages to file or event log.

**Comment by okynos** [comment]
Yes, I will include better logging on my part, but in the case an unwrap over a None or another unexpected situation happens (Where the Rust backtrace spam) There is no way to retrieve such output?

**Comment by faern** [comment]
You can use [`log-panics`](https://crates.io/crates/log-panics) to set up a global panic handler that uses the `log` macros instead of just printing panics to stderr. This way when you have set up a proper file logger the panics will end up in that file.

**Comment by okynos** [comment]
> You can use [log-panics](https://crates.io/crates/log-panics) to set up a global panic handler that uses the log macros instead of just printing panics to stderr. This way when you have set up a proper file logger the panics will end up in that file.

I didn't know this crate, will review it thank you!
